# Generated by Django 5.2.7 on 2025-11-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('prep_time', models.CharField(max_length=50)),
                ('serves', models.CharField(max_length=50)),
                ('ingredients', models.JSONField(default=list)),
                ('calories', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('carbs', models.CharField(max_length=50)),
                ('fat', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
                ('extra_toppings', models.ManyToManyField(blank=True, to='menu.extratopping')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
