# Generated by Django 5.2.7 on 2025-11-11 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_customizable_spice_menuitem_spice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
