# Generated by Django 5.2.7 on 2025-11-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_image'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item_category',
            new_name='cached_item_category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item_description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cached_item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
