# Generated by Django 5.2.7 on 2025-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_menu_item_category_orderitem_cached_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
