# Generated by Django 5.2.7 on 2025-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_spice_level',
            field=models.CharField(choices=[('milder', 'Milder than default'), ('default', 'As prepared'), ('spicier', 'Spicier than default'), ('extra_spicy', 'Extra Spicy')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='spice_notes',
            field=models.TextField(blank=True),
        ),
    ]
